//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedAnalysis) DeepCopyInto(out *FeedAnalysis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedAnalysis.
func (in *FeedAnalysis) DeepCopy() *FeedAnalysis {
	if in == nil {
		return nil
	}
	out := new(FeedAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeedAnalysis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedAnalysisList) DeepCopyInto(out *FeedAnalysisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeedAnalysis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedAnalysisList.
func (in *FeedAnalysisList) DeepCopy() *FeedAnalysisList {
	if in == nil {
		return nil
	}
	out := new(FeedAnalysisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeedAnalysisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedAnalysisSpec) DeepCopyInto(out *FeedAnalysisSpec) {
	*out = *in
	in.FeedScraper.DeepCopyInto(&out.FeedScraper)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedAnalysisSpec.
func (in *FeedAnalysisSpec) DeepCopy() *FeedAnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(FeedAnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedAnalysisStatus) DeepCopyInto(out *FeedAnalysisStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedAnalysisStatus.
func (in *FeedAnalysisStatus) DeepCopy() *FeedAnalysisStatus {
	if in == nil {
		return nil
	}
	out := new(FeedAnalysisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedScraper) DeepCopyInto(out *FeedScraper) {
	*out = *in
	if in.FeedsUrl != nil {
		in, out := &in.FeedsUrl, &out.FeedsUrl
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedScraper.
func (in *FeedScraper) DeepCopy() *FeedScraper {
	if in == nil {
		return nil
	}
	out := new(FeedScraper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNews) DeepCopyInto(out *LocalNews) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNews.
func (in *LocalNews) DeepCopy() *LocalNews {
	if in == nil {
		return nil
	}
	out := new(LocalNews)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNewsApp) DeepCopyInto(out *LocalNewsApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNewsApp.
func (in *LocalNewsApp) DeepCopy() *LocalNewsApp {
	if in == nil {
		return nil
	}
	out := new(LocalNewsApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalNewsApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNewsAppList) DeepCopyInto(out *LocalNewsAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LocalNewsApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNewsAppList.
func (in *LocalNewsAppList) DeepCopy() *LocalNewsAppList {
	if in == nil {
		return nil
	}
	out := new(LocalNewsAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalNewsAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNewsAppSpec) DeepCopyInto(out *LocalNewsAppSpec) {
	*out = *in
	out.NewsBackend = in.NewsBackend
	in.FeedScraper.DeepCopyInto(&out.FeedScraper)
	out.NewsFrontend = in.NewsFrontend
	out.Postgis = in.Postgis
	out.Extractor = in.Extractor
	out.LocalNews = in.LocalNews
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNewsAppSpec.
func (in *LocalNewsAppSpec) DeepCopy() *LocalNewsAppSpec {
	if in == nil {
		return nil
	}
	out := new(LocalNewsAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNewsAppStatus) DeepCopyInto(out *LocalNewsAppStatus) {
	*out = *in
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNewsAppStatus.
func (in *LocalNewsAppStatus) DeepCopy() *LocalNewsAppStatus {
	if in == nil {
		return nil
	}
	out := new(LocalNewsAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationExtractor) DeepCopyInto(out *LocationExtractor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationExtractor.
func (in *LocationExtractor) DeepCopy() *LocationExtractor {
	if in == nil {
		return nil
	}
	out := new(LocationExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewsBackend) DeepCopyInto(out *NewsBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewsBackend.
func (in *NewsBackend) DeepCopy() *NewsBackend {
	if in == nil {
		return nil
	}
	out := new(NewsBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewsFrontend) DeepCopyInto(out *NewsFrontend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewsFrontend.
func (in *NewsFrontend) DeepCopy() *NewsFrontend {
	if in == nil {
		return nil
	}
	out := new(NewsFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Postgis) DeepCopyInto(out *Postgis) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Postgis.
func (in *Postgis) DeepCopy() *Postgis {
	if in == nil {
		return nil
	}
	out := new(Postgis)
	in.DeepCopyInto(out)
	return out
}
