apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mng-feedscaper-rolebinding
subjects:
- kind: ServiceAccount
  namespace: attempt2
  name: feed-scraper-sa
roleRef:
  kind: ClusterRole
  name: mng-feedscaper-role
  apiGroup: rbac.authorization.k8s.io