apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynewsapp-crd
  namespace: argocd
spec:
  destination:
    namespace: localnews-gitops-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/operator/gitops/crd
    repoURL: git@github.com:Apress/Kubernetes-Native-Development.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
