apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynewsapp-olm
  namespace: argocd
spec:
  destination:
    namespace: operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/operator/gitops/olm
    repoURL: https://github.com/sa-mw-dach/local-news-shift.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
