FROM registry.access.redhat.com/ubi8/python-38

WORKDIR /opt/app-root/src

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt && python -m spacy download en_core_web_md

COPY src/server.py /opt/app-root/src/src/server.py

EXPOSE 5000

ENTRYPOINT ["python", "-X", "utf8", "-u", "src/server.py"]