{{ if eq .Values.locationextractor.deployment "on" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.locationextractor.name }}
    version: v1
  name: {{ .Values.locationextractor.name }}
spec:
  replicas: {{ .Values.locationextractor.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.locationextractor.name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.locationextractor.name }}
        version: v1
      annotations:
        {{ if eq .Values.locationextractor.servicemesh "true" }}
        sidecar.istio.io/inject: "true"
        {{ end }}
    spec:
      containers:
        - image: {{ .Values.locationextractor.image }}:{{ .Values.locationextractor.imageTag }}
          name: {{ .Values.locationextractor.name }}
          imagePullPolicy: {{ .Values.localnews.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.locationextractor.ports.containerPort }}
{{ end }}
