---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventlistener-role
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "clusterinterceptors", "triggerbindings", "triggertemplates", "taskruns", "pipelineruns"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "apply"]
- apiGroups: ["tekton.dev"]
  resources: ["taskruns", "pipelineruns"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "apply"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventlistener-binding
subjects:
- kind: ServiceAccount
  name: event-listener-sa
  namespace: localnews-pipelines
roleRef:
  kind: ClusterRole
  name: eventlistener-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-listener-sa