# permissions for end users to view feedanalysis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feedanalysis-viewer-role
rules:
- apiGroups:
  - kubdev.apress.com
  resources:
  - feedanalysis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubdev.apress.com
  resources:
  - feedanalysis/status
  verbs:
  - get
