# permissions for end users to edit feedanalysis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feedanalysis-editor-role
rules:
- apiGroups:
  - kubdev.apress.com
  resources:
  - feedanalysis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubdev.apress.com
  resources:
  - feedanalysis/status
  verbs:
  - get
