# permissions for end users to view localnewsapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localnewsapp-viewer-role
rules:
- apiGroups:
  - kubdev.apress.com
  resources:
  - localnewsapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubdev.apress.com
  resources:
  - localnewsapps/status
  verbs:
  - get
