#
# Build stage
#
FROM registry.access.redhat.com/ubi8/openjdk-11 AS build
WORKDIR /home/jboss
COPY src /home/jboss/src
COPY pom.xml /home/jboss
RUN mvn -f /home/jboss/pom.xml clean package
#
# Package stage
#
FROM registry.access.redhat.com/ubi8/openjdk-11-runtime
COPY --from=build /home/jboss/target/feed-scraper-jar-with-dependencies.jar /usr/local/lib/feed-scraper.jar
ENTRYPOINT ["java","-jar","/usr/local/lib/feed-scraper.jar"]