apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mng-feedscaper-rolebinding
subjects:
- kind: ServiceAccount
  name: news-backend-sa
roleRef:
  kind: Role
  name: mng-feedscaper-role
  apiGroup: rbac.authorization.k8s.io