apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-role
rules:
  - verbs:
      - get
      - create
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
