apiVersion: v1
kind: Service
metadata:
  labels:
    app: news-frontend
  name: news-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31111
  selector:
    app: news-frontend
  type: NodePort

