apiVersion: v1
kind: Service
metadata:
  labels:
    app: news-backend
  name: news-backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: news-backend
