---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-new-push-listener
spec:
  triggers:
    - name: github-new-push-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - name: "only deploy on pushes to openshift branch"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref in ['refs/heads/openshift']"
      bindings:
        - ref: github-push-binding
      template:
        ref: github-push-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: event-listener-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: imageversion
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: image_repo
      value: $(body.image_repo)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-push-template
spec:
  params:
  - name: imageversion
    description: The Image Tag of the Container Image
    default: main
  - name: image_repo
    description: The Container Registry and Container Repository to be used
    default: quay.io/k8snativedev
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: news-backend-simple-pipe-run-
      namespace: localnews-pipelines
      labels:
        tekton.dev/pipeline: news-backend-simple-pipe
    spec:
      params:
        - name: message
          value: $(tt.params.message)
        - name: contenttype
          value: $(tt.params.contenttype)
        - name: image_repo
          value: $(tt.params.image_repo)
        - name: image_version
          value: $(tt.params.imageversion)
        - name: gitrepositoryurl
          value: $(tt.params.gitrepositoryurl)
        - name: gitrevision
          value: openshift
      pipelineRef:
        name: news-backend-simple-pipe-gitops
      serviceAccountName: pipeline
      workspaces:
        - name: shared-workspace
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - emptyDir: {}
          name: maven-settings