apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: news-frontend-build-pipe
spec:
  params:
    - name: component
      type: string
      description: The name of the component to build
      default: news-frontend
    - name: image_repo
      type: string
      description: The image repository to push the resulting image to
      default: quay.io/k8snativedev
    - name: image_version
      type: string
      description: The image version
      default: latest
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
      default: git@github.com:Apress/Kubernetes-Native-Development.git
    - name: dockerfile
      type: string
      description: The name of the dockerfile to build
      default: ./Dockerfile.build-single 
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-sources
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.gitrepositoryurl)
        - name: revision 
          value: $(params.gitrevision)
        - name: deleteExisting
          value: 'true'
        - name: submodules
          value: "false"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: npm-install
      taskRef:
        name: npm
      params:
        - name: PATH_CONTEXT
          value: components/$(params.component)
        - name: ARGS
          value: 
            - install 
      runAfter:
        - clone-sources
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: npm-build
      taskRef:
        name: npm
      params:
        - name: PATH_CONTEXT
          value: components/$(params.component)
        - name: ARGS
          value: 
            - run 
            - build
            - --configuration=staging
      runAfter:
        - npm-install
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-and-push-image
      taskRef:
        name: buildah
      params:
        - name: CONTEXT
          value: components/$(params.component)
        - name: BUILDER_IMAGE
          value: quay.io/buildah/stable:v1.21.0
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: PUSH_EXTRA_ARGS
          value: --log-level warn
        - name: TLSVERIFY
          value: "true"
        - name: IMAGE
          value: $(params.image_repo)/news-frontend:$(params.image_version)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - npm-build