apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: localnews-operator-sub
  namespace: operators
spec:
  channel: alpha
  name: news-operator-helm 
  source: localnews-catalog 
  sourceNamespace: operators
