apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-extractor
  name: location-extractor
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: location-extractor
status:
  loadBalancer: {}
