{{ if eq .Values.newsbackend.deployment "on" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.newsbackend.name }}
  name: {{ .Values.newsbackend.name }}
spec:
  replicas: {{ .Values.newsbackend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.newsbackend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.newsbackend.name }}
    spec:
      containers:
        - env:
            - name: {{ .Values.newsbackend.envVars.backendNlpUrl.key }}
              value: {{ .Values.newsbackend.envVars.backendNlpUrl.valueHost }}:{{ .Values.locationextractor.ports.servicePort }}{{ .Values.newsbackend.envVars.backendNlpUrl.valueEndpoint }}
            - name: {{ .Values.newsbackend.envVars.jdbcUrl.key }}
              value: {{ .Values.newsbackend.envVars.jdbcUrl.value }}
          image: {{ .Values.newsbackend.image }}:{{ .Values.newsbackend.imageTag }}
          imagePullPolicy: {{ .Values.localnews.imagePullPolicy }}
          name: {{ .Values.newsbackend.name }}
          ports:
            - containerPort: {{ .Values.newsbackend.ports.containerPort }}
{{ end }}