apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.postgis.name }}
  name: {{ .Values.postgis.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgis.name }}
    spec:
      containers:
        - env:
            - name: {{ .Values.postgis.envVars.PGDATA.key }}
              value: {{ .Values.postgis.envVars.PGDATA.value }}
            - name: {{ .Values.postgis.envVars.POSTGRES_DB.key }}
              value: {{ .Values.postgis.envVars.POSTGRES_DB.value }}
            - name: {{ .Values.postgis.envVars.POSTGRES_PASSWORD.key }}
              value: {{ .Values.postgis.envVars.POSTGRES_PASSWORD.value }}
            - name: {{ .Values.postgis.envVars.POSTGRES_USER.key }}
              value: {{ .Values.postgis.envVars.POSTGRES_USER.value }}
          image: {{ .Values.postgis.image }}
          imagePullPolicy: {{ .Values.localnews.imagePullPolicy }}
          name: {{ .Values.postgis.name }}
          ports:
            - containerPort: {{ .Values.postgis.ports.containerPort }}
