apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.postgis.name }}
  name: {{ .Values.postgis.name }}
spec:
  ports:
    - port: {{ .Values.postgis.ports.servicePort }}
      targetPort: {{ .Values.postgis.ports.containerPort }}
  selector:
    app: {{ .Values.postgis.name }}
