# This Task will do a helm uninstall based on the given helm release
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-uninstall
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/categories: Deployment
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: helm
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    These tasks will install / upgrade a helm chart into your Kubernetes /
    OpenShift Cluster using Helm
  params:
    - name: release_name
      description: The helm release name
      default: "helm-release"
    - name: release_namespace
      description: The helm release namespace
      default: ""
    - name: helm_image
      description: "Specify a specific helm image"
      default: "docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae" #tag: v3.6.0
  steps:
    - name: upgrade-from-repo
      image: $(params.helm_image)
      script: |
        echo current installed helm releases
        helm list --namespace "$(params.release_namespace)"
        echo uninstalling helm chart...
        helm uninstall --namespace "$(params.release_namespace)" $(params.release_name) --debug