kind: Secret
apiVersion: v1
metadata:
  name: registry-creds
  namespace: localnews-pipelines
  annotations:
    tekton.dev/docker-0: 'https://docker.io'
data:
# creds deactivated, just for demonstration
  .dockerconfigjson: >-
    eyJhdXRocy000I6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJtYXhpc3NlcyIsInBhc3N3b3JkIjoiZGNrcl9wYXRfa0V5blZ6UUZZUkRhUnlGYnNVUTRyX3Z0NkswIiwiZW1haWwiOiJtYXhfZGFyZ2F0ekBob3RtYWlsLmNvbSIsImF1dGgiOiJiV0Y0YVhOelpYTTZaR05yY2w5d1lYUmZhMFY1YmxaNlVVWlpVa1JoVW5sR1luTlZVVFJ5WDNaME5rc3cifX19
type: kubernetes.io/dockerconfigjson