apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localnews
spec:
  source:
    path: k8s/helm-chart
    repoURL: https://github.com/Apress/Kubernetes-Native-Development.git
    targetRevision: openshift
  destination:
    namespace: localnews
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default