# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

localnews:
  imagePullPolicy: Always
  minikubeIp: fill-in-minikube-ip
  domain: nip.io

feedscraper:
  deployment: "on"
  name: feed-scraper
  replicaCount: 1
  image: quay.io/k8snativedev/feed-scraper
  imageTag: latest
  envVars:
    feeds:
      key: SCRAPER_FEEDS_URL
      value: http://feeds.bbci.co.uk/news/world/rss.xml
    backend:
      key: SCRAPER_FEED_BACKEND_HOST
      value: news-backend

newsbackend:
  deployment: "on"
  service: "on"
  name: news-backend
  replicaCount: 1
  image: quay.io/k8snativedev/news-backend
  imageTag: latest
  ports:
    containerPort: 8080
    servicePort: 8080
    nodePort: 30000
  envVars:
    backendNlpUrl:
      key: backend.nlp.url
      valueHost: "http://location-extractor"
      valueEndpoint: /get_loc
    jdbcUrl:
      key: quarkus.datasource.jdbc.url
      value: jdbc:postgresql://postgis:5400/news?user=postgres&password=banane

postgis:
  name: postgis
  replicaCount: 1
  image: postgis/postgis:12-master
  ports:
    containerPort: 5432
    servicePort: 5400
  envVars:
    PGDATA:
      key: PGDATA
      value: /tmp/pgdata
    POSTGRES_DB:
      key: POSTGRES_DB
      value: news
    POSTGRES_PASSWORD:
      key: POSTGRES_PASSWORD
      value: banane
    POSTGRES_USER:
      key: POSTGRES_USER
      value: postgres

locationextractor:
  deployment: "on"
  service: "on"
  name: location-extractor
  replicaCount: 1
  image: quay.io/k8snativedev/location_extractor
  imageTag: latest
  ports:
    containerPort: 80
    servicePort: 8081
    
newsfrontend:
  deployment: "on"
  service: "on"
  name: news-frontend
  replicaCount: 1
  image: quay.io/k8snativedev/news-frontend
  imageTag: latest
  ports:
    containerPort: 80
    servicePort: 80
    nodePort: 31111
  backendConnection: "viaNodePort" # alternative is "viaIngress" which requires to fill in minikube ip if running on minikube at localnews.minikubeIp
  envVars:
    backend:
      ip:
        key: NODE_IP
        value: # with "viaNodePort" no value needs to be set because ip is retrieved from kubernetes api"
      nodePort:
        key: NODE_PORT
        value: # with "viaNodePort" no value needs to be set because nodePort is specified in the news-backend Service"
