{{ if eq .Values.localnews.workloadmonitoring "on" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: duplicates-alert
spec:
  groups:
  - name: news-backend
    rules:
    - alert: TooManyDuplicatesAlert
      expr: application_duplicateFeeds > 50
      annotations:
        summary: Too many duplicates detected
{{ end }}
          
