apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
stringData:
  ### key is just for demonstration purpose and deactivated
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA9rAT1aOXUZPZHZ5NUETEdJ+vm+5dgJFGvzcXEwuriawAAAJBJXipOSV4q
    TgAAAAtzc2gtZWQyNTUxOQAAACA9rAT1aOXUZPZHZ5NUETEdJ+vm+5dgJFGvzcXEwuriaw
    AAAEBjNttAnXuTl0PUQQCTdKHp+ttKWjhXENdx3+dXMnwOMD2sBPVo5dRk9kdnk1QRMR0n
    6+b7l2AkUa/NxcTC6uJrAAAADG9jcEB0ZXN0LmNvbQE=
    -----END OPENSSH PRIVATE KEY-----