apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-binding
subjects:
- kind: ServiceAccount
  name: clone-and-build-bot
  namespace: localnews-pipelines
roleRef:
  kind: ClusterRole
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io