apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-scraper
  template:
    metadata:
      labels:
        app: feed-scraper
    spec:
      containers:
        - command:
            - java
            - -jar
            - /usr/local/lib/feed-scraper.jar
          image: quay.io/k8snativedev/feed-scraper
          name: feed-scraper
          env:
            - name: SCRAPER_FEED_BACKEND_HOST
              value: news-backend