apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-pv
  labels:
    type: local
spec:
  storageClassName: ocs-storagecluster-cephfs
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
