apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
data:
  404.html: |
    <html>
    	<body>This page cannot be found, guys!</body>
    </html>
  my.conf: |
    server {
      listen       8080;
      listen  [::]:8080;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      error_page   404              /404.html;
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
