apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: news-backend
  name: news-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-backend
  template:
    metadata:
      labels:
        app: news-backend
        dev: "true"
    spec:
      containers:
        - env:
            - name: backend.nlp.url
              value: http://location-extractor/get_loc
            - name: quarkus.datasource.jdbc.url
              value: jdbc:postgresql://postgis:5400/news?user=postgres&password=banane
            - name: QUARKUS_LAUNCH_DEVMODE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['dev']
          image: quay.io/k8snativedev/news-backend:latest-dev
          name: news-backend
          ports:
            - containerPort: 8080
